application: ivetappedthatapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: mainPage.application

- url: /tappedlist
  script: tappedlist.application

- url: /beerdb
  script: beerDB.application

- url: /beerdb/.*
  script: beerDB.application

- url: /.*
  script: mainPage.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest